Convert CaseInsensitiveDict response headers to dict
Requests by default makes the response headers into it's own custom type,
`CaseInsensitiveDict`, which can't be JSON serialized without extra work.
This affects the `dog timeboard show ...` and `dog screenboard show ...`
commands, as they JSON encode the Python data structures and they will give
the following error message without this change:

    TypeError: Object of type CaseInsensitiveDict is not JSON serializable

This fixes it by explictly converting the response headers object to a dict
before being added to the response object.